security:
    oauth2:
        resource:
            filter-order: 3
server:
    address: 0.0.0.0
    port: 8443
spring:
    mail:
        host: smtp.gmail.com
        password: aaaa
        username: kevindreyar@gmail.com
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

    data:
      mongodb:
        database: celhumid
        host: localhost
#        host: 192.168.0.108
        port: 27017
    datasource:
        password: Fuller70n$
        url: jdbc:mysql://localhost:3306/celhumtravel?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
#        url: jdbc:mysql://192.168.0.108:3306/celhumtravel?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
        username: root
#        username: fullertonid
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect

